FROM etable/php7.0.8

ENV DOCKER_UID=1000 \
    DOCKER_GID=1000

COPY ./dist/certificate.crt /usr/local/share/ca-certificates/extra/composer.crt

RUN update-ca-certificates --fresh &&\
    echo "Installing composer \n" &&\
    curl https://getcomposer.org/installer -o /usr/local/share/ca-certificates/extra/composer.crt > /tmp/composer-setup.php &&\
    php /tmp/composer-setup.php --install-dir=/bin --filename=composer &&\
    rm -rf /tmp/cpmposer-setup.php &&\
    chmod +x /bin/composer

COPY ./entrypoint/develop_entrypoint.sh /usr/local/bin/entrypoint.sh

RUN echo "Fixing Permissions on Entrypoint Script \n" &&\
    chown root:root /usr/local/bin/entrypoint.sh &&\
    chmod +x /usr/local/bin/entrypoint.sh &&\
    usermod --shell /bin/bash www-data

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["php-fpm"]