version: 0.2

env:
  variables: 
    VERSION_PHP_72: 202012161534
    VERSION_PHP_708: 202012161534

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
   commands:
     - docker login -u $USER -p $TOKEN
  build:
    commands:
     - docker build -f ./dockerfiles/7.0.8/Dockerfile -t etable/php7.0.8:${VERSION_PHP_708} -t etable/php7.0.8:latest
     - docker build -f ./dockerfiles/7.0.8/Dockerfile_develop -t etable/php7.0.8-dev:${VERSION_PHP_708} -t etable/php7.0.8-dev:latest
     - docker build -f ./dockerfiles/7.2/Dockerfile -t etable/php7.0.8:${VERSION_PHP_72} -t etable/php7.0.8:latest
     - docker build -f ./dockerfiles/7.2/Dockerfile_develop -t etable/php7.0.8-dev:${VERSION_PHP_72} -t etable/php7.0.8-dev:latest 
  post_build:
    commands:
      - docker push etable/php7.2
      - docker push etable/php7.2-dev
      - docker push etable/php7.0.8
      - docker push etable/php7.0.8-dev