version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
   commands:
     - docker login -u $USER -p $TOKEN
     - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 251998751921.dkr.ecr.eu-central-1.amazonaws.com
  build:
    commands:   
     # PHP 7.0.8
     - docker build -f ./dockerfiles/7.0.8/Dockerfile -t etable/php7.0.8:$(cat VERSION_PHP_708) -t etable/php7.0.8:latest .
     - docker build -f ./dockerfiles/7.0.8/Dockerfile_develop -t etable/php7.0.8-dev:$(cat VERSION_PHP_708) -t etable/php7.0.8-dev:latest -t 251998751921.dkr.ecr.eu-central-1.amazonaws.com/php708:$(cat VERSION_PHP_708) -t 251998751921.dkr.ecr.eu-central-1.amazonaws.com/php708:latest .
     
     # PHP 72
     - docker build -f ./dockerfiles/7.2/Dockerfile -t etable/php7.2:$(cat VERSION_PHP_72) -t etable/php7.2:latest -t 251998751921.dkr.ecr.eu-central-1.amazonaws.com/php72:$(cat VERSION_PHP_72) -t 251998751921.dkr.ecr.eu-central-1.amazonaws.com/php72:latest .
     - docker build -f ./dockerfiles/7.2/Dockerfile_develop -t etable/php7.2-dev:$(cat VERSION_PHP_72) -t etable/php7.2-dev:latest .
     
     # PHP80
     - docker build -f ./dockerfiles/80/Dockerfile -t etable/php8.0:$(cat VERSION_PHP_80) -t etable/php80:latest -t 251998751921.dkr.ecr.eu-central-1.amazonaws.com/php80:$(cat VERSION_PHP_80) -t 251998751921.dkr.ecr.eu-central-1.amazonaws.com/php80:latest .
     - docker build -f ./dockerfiles/80/Dockerfile_develop -t etable/php8.0-dev:$(cat VERSION_PHP_80) -t etable/php8.0-dev:latest .

     # Nodejs
     - docker build -f ./dockerfiles/nodejs/Dockerfile -t etable/nodejs:$(cat VERSION_NODEJS) -t etable/nodejs:latest -t 251998751921.dkr.ecr.eu-central-1.amazonaws.com/nodejs:$(cat VERSION_NODEJS) -t 251998751921.dkr.ecr.eu-central-1.amazonaws.com/nodejs:latest .
     
     - bash tests/test_composer.sh
     
     # Pushing PHP 72
     - docker push etable/php7.2
     - docker push 251998751921.dkr.ecr.eu-central-1.amazonaws.com/php72
     - docker push etable/php7.2-dev

     # Pushing PHP 708
     - docker push etable/php7.0.8
     - docker push 251998751921.dkr.ecr.eu-central-1.amazonaws.com/php708
     - docker push etable/php7.0.8-dev

     # Pushing php80
     - docker push etable/php80
     - docker push 251998751921.dkr.ecr.eu-central-1.amazonaws.com/php80
     - docker push etable/php80-dev

     # Pushing Nodejs
     - docker push 251998751921.dkr.ecr.eu-central-1.amazonaws.com/nodejs
     - docker push etable/nodejs

