version: "3.7"

services:
  base72:
    image: etable/php7.2:latest
    entrypoint: "php-fpm"
    volumes:
      - "./www:/var/www/html"

  develop72:
    image: etable/php7.2-dev:latest
    volumes:
      - "./www:/var/www/html"
  
  supervisor:
    image: etable/php7.2-supervisor:latest
    volumes:
      - "./www:/var/www/html"
      - "./dist/supervisor_dummy_service.conf:/etc/supervisor/conf.d:ro"

  base708:
    image: etable/php7.0.8:latest
    volumes:
      - "./www:/var/www/html"

  nginx:
    image: nginx:alpine
    ports:
      - 7880:7880
      - 7881:7881
      - 7882:7882
    links:
      - "develop72:develop72"
      - "base708:base708"
    volumes:
      - "./www:/var/www/html"
      - "./dist/nginx.conf:/etc/nginx/nginx.conf:ro"
